version: "2"
services:
  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - 8083:8083
      - 8086:8086
      - 8090:8090
    environment:
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=secretpassword
    networks:
      - monitoring
    volumes:
      - /influxdb_data:/var/lib/influxdb
  telegraf:
    image: telegraf
    container_name: telegraf
    networks:
      - monitoring
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    env_file:
      - 'env.grafana'
    networks:
      - monitoring
    volumes:
      - /grafana_data:/var/lib/grafana

networks:
  monitoring:
