version: "3.8"
services:
  influxdb:
    image: influxdb:1.7.10-alpine
    container_name: influxdb
    ports:
      - 8083:8083
      - 8086:8086
      - 8090:8090
    environment:
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=secretpassword
    networks:
      - monitoring
    volumes:
      - /influxdb_data:/var/lib/influxdb
  telegraf:
    image: telegraf:1.12.6-alpine
    container_name: telegraf
    networks:
      - monitoring
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
  grafana:
    image: grafana/grafana:6.6.0
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - monitoring
networks:
  monitoring:
