language: java

jdk:
  - oraclejdk11

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - npm i -g npm@6.7.0

branches:
  only:
    - master
    - travis

script:
  - ./gradlew clean build

before_deploy:
  - echo $TEST_IP
  - ssh-keyscan -t $TRAVIS_SSH_KEY_TYPES -H $TEST_IP 2>&1 | tee -a $HOME/.ssh/known_hosts
  - ssh-keyscan -t $TRAVIS_SSH_KEY_TYPES -H $PROD_IP 2>&1 | tee -a $HOME/.ssh/known_hosts
  - echo "${SSH_KEY}" | base64 --decode >/tmp/deploy_rsa
  - echo "${PROD_SSH}" | base64 --decode >/tmp/prod_ssh
  - chmod 600 /tmp/deploy_rsa
  - chmod 600 /tmp/prod_ssh
  - chmod +x scripts/deploy.sh

deploy:
  provider: script
  script: ./scripts/deploy.sh test ${TEST_IP}
  skip_cleanup: true
  on:
    branch: develop
  provider: script
  script: ./scripts/deploy.sh prod ${PROD_IP}
  skip_cleanup: true
  on:
    branch: travis