addons:
  ssh_known_hosts: TEST_IP
  ssh_known_hosts: PROD_IP

language: java

jdk:
  - oraclejdk11

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - npm i -g npm@6.7.0

branches:
  only:
    - master
    - travis

script:
  - ./gradlew clean build

before_deploy:
  - echo "${SSH_KEY}" | base64 --decode >/tmp/deploy_rsa
  - chmod 600 /tmp/deploy_rsa
  - chmod +x scripts/deploy.sh

deploy:
  provider: script
  script: ./scripts/deploy.sh TEST_IP
  skip_cleanup: true
  on:
    branch: develop
  provider: script
  script: ./scripts/deploy.sh PROD_IP
  skip_cleanup: true
  on:
    branch: travis