spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/test
    username: test
    password: MDYwNTIwMTlxd2VydHkK

logging:
  level:
    com:
      zaxxer:
        hikari:
          HikariConfig: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    chat:
      tamtam:
        bot: DEBUG

tamtam:
  host: http://89.208.84.173
