spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${spring.datasource.username}
    username: prod_database
    password: QUFNRXNlY3JldDA0MDUyMDE5MzA4Cg==
  servlet:
    multipart:
      max-file-size: 1000MB

tamtam:
  host: http://89.208.84.33
  bot:
    registration:
      id: 574046867817
      url: https://tt.me/TamTamRegistrationBot
      token: TsK1Wo4n5vqy1vLq3fXUqSbw2_kT0BcYc-DBNQyZR-4
      enabledIds: 555537636725, 590435433004, 575868018573, 577949140156
    hockey2019:
      id: 593077348372
      url: https://tt.me/IceHockey2019
      token: Oj6kkmCdCyTBMYHJC_8RimGuRatU3pLv8Md6xu9j4h0