spring:
  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: true
  datasource:
    url: jdbc:hsqldb:file:testdb;sql.syntax_pgs=true
    username: sa
    password:

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
    chat:
      tamtam:
        bot: DEBUG

tamtam:
  host: http://89.208.84.173
