spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: false
        format_sql: false
    open-in-view: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:hsqldb:mem:testdb;sql.syntax_pgs=true;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    username: sa
    password:
    hikari:
      idle-timeout: 10000
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

logging:
  level:
    org:
      springframework: INFO
      hibernate:
        SQL: OFF
        type: OFF
    chat:
      tamtam:
        bot: INFO

server:
  address: 0.0.0.0
  port: 8090

tamtam:
  host: http://localhost:8090
  chat:
    listSizeThreshold: 20
    chatsFetchAmount: 20
  registration:
    bot:
      url: https://tt.me/BuilderRegBot
      id: 581483330212
      token: JUeixE5Dr7WoBY3ajjfwr72ya1CR_zw6D25VlR0sgNI
      enabledIds: 555537636725, 590435433004, 575868018573, 577949140156
  broadcast:
    executor:
      corePoolSize: 2
      maxPoolSize: 4
