spring:
  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: true
  datasource:
    url: jdbc:hsqldb:file:testdb;sql.syntax_pgs=true
    username: sa
    password:

logging:
  level:
    com:
      zaxxer:
        hikari:
          HikariConfig: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    chat:
      tamtam:
        bot: DEBUG