spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.H2
  datasource:
    url: jdbc:h2:./dev_db/testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
logging:
  level:
    com:
      zaxxer:
        hikari:
          HikariConfig: DEBUG
    org:
      hibernate:
        SQL: 'off'
        type:
          descriptor:
            sql:
              BasicBinder: 'off'
        tool:
          schema:
            internal: error
    chat:
      tamtam:
        bot: DEBUG