spring:
  profiles:
    active: development
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  address: 0.0.0.0
  port: 8090

---

spring:
  profiles: development
  datasource:
    url: jdbc:hsqldb:file:~/db/Server
    username: developer
    password: developer
    driverClassName: org.hsqldb.jdbcDriver

---

spring:
  profiles: production
  datasource:
    url: jdbc:hsqldb:mem:Server;sql.syntax_pgs=true
    username: production
    password: production
    driverClassName: org.hsqldb.jdbcDriver

---

tamtam:
  registration:
    bot:
      id: 581483330212
      token: JUeixE5Dr7WoBY3ajjfwr72ya1CR_zw6D25VlR0sgNI
      botType: Registration
      trustedUsers: 555537636725, 574784047321, 590435433004, 575868018573