spring:
  profiles:
    active: development
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: chatbot-constructor
logging:
  level:
    org:
      springframework: INFO
      hibernate:
        SQL: DEBUG
        type: TRACE
    chat:
      tamtam:
        bot: DEBUG
  file: ${spring.application.name}
server:
  address: 0.0.0.0
  port: 8090

---

spring:
  profiles: development
  datasource:
    url: jdbc:hsqldb:file:~/db/Server
    username: developer
    password: developer
    driverClassName: org.hsqldb.jdbcDriver

---

spring:
  profiles: production
  datasource:
    url: jdbc:hsqldb:mem:Server;sql.syntax_pgs=true
    username: production
    password: production
    driverClassName: org.hsqldb.jdbcDriver

---

tamtam:
  host: http://localhost:8090
  chat:
    listSizeThreshold: 20
    chatsFetchAmount: 20
  registration:
    bot:
      id: 581483330212
      token: JUeixE5Dr7WoBY3ajjfwr72ya1CR_zw6D25VlR0sgNI
      botType: Registration
      onlyTrustedUsers: true
      trustedUsers: 555537636725, 590435433004, 575868018573, 577949140156
  broadcast:
    executor:
      corePoolSize: 2
      maxPoolSize: 4
