spring:
  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: true
  datasource:
    url: jdbc:hsqldb:file:testdb;sql.syntax_pgs=true
    username: sa
    password:

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
    chat:
      tamtam:
        bot: DEBUG

tamtam:
  registration:
    bot:
      id: 592946665497
      token: JTY864IytlNJaW38XFn2WYC-Jikm0mv5PeewS_ugaYU