spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${spring.datasource.username}
    username: prod_database
    password: QUFNRXNlY3JldDA0MDUyMDE5MzA4Cg==
  servlet:
    multipart:
      max-file-size: 1000MB