version: '3.7'
services:
  app:
    build: .
    container_name: app
    restart: always
    ports:
      - 80:8090
    networks:
      - default
    depends_on:
      - db
      - consul
    logging:
      options:
        max-size: "100m"
        max-file: "3"
  db:
    container_name: db
    image: library/postgres:12.2
    restart: unless-stopped
    volumes:
      - data:/var/lib/postgresql/data/
    env_file: db.env
    ports:
      - 5432:5432
    networks:
      - default
  consul:
    container_name: consul
    image: library/consul:1.7.3
    restart: unless-stopped
    ports:
      - 8500:8500
    command: agent -ui -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect 1

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

volumes:
  data: