# config path: config/chatbot-constructor/data
tamtam:
  bot:
    registration:
      id: 574046867817
      url: https://tt.me/TamTamRegistrationBot
      token: TsK1Wo4n5vqy1vLq3fXUqSbw2_kT0BcYc-DBNQyZR-4
      enabledIds: 555537636725, 590435433004, 575868018573, 577949140156
    hockey2019:
      id: 593077348372
      url: https://tt.me/IceHockey2019
      token: Oj6kkmCdCyTBMYHJC_8RimGuRatU3pLv8Md6xu9j4h0
