# config path: config/chatbot-constructor/data
tamtam:
  bot:
    registration:
      url: https://tt.me/BuilderRegBot
      id: 581483330212
      token: JUeixE5Dr7WoBY3ajjfwr72ya1CR_zw6D25VlR0sgNI
      enabledIds: 555537636725, 590435433004, 575868018573, 577949140156
    hockey2019:
      url: https://tt.me/Hockey2019
      id: 579249368771
      token: _WJ5Jt0ksotmic5llAnm7DJNvXO8WAce8AIBpLGVW-o
      external_url:
        news: https://sport.mail.ru/inf/json_vk_bot_competition/hockey2019/news
        news_team: https://sport.mail.ru/inf/json_vk_bot_competition/hockey2019/news/{id}
        calendar: https://sport.mail.ru/inf/json_vk_bot_competition/hockey2019/calendar
        results: https://sport.mail.ru/inf/json_vk_bot_competition/hockey2019/results
        match: https://sport.mail.ru/inf/json_vk_bot_competition/hockey2019/match/{id}
  broadcast:
    enabled: true
  rss:
    enabled: true
    bot:
      token: Iu9O0wVu2dtllKK8MV-Sw9gbFMkM8Z5cLYCTnl8PMGg
    feeds:
      - enabled: false
        channel: -70694478588716
        url: https://twitrss.me/twitter_user_to_rss/?user=wylsacom
        format: title-link