# config path: config/chatbot-constructor/data
tamtam:
  bot:
    registration:
      url: https://tt.me/BuilderRegBot
      id: 581483330212
      token: JUeixE5Dr7WoBY3ajjfwr72ya1CR_zw6D25VlR0sgNI
      enabledIds: 555537636725, 590435433004, 575868018573, 577949140156
    hockey2019:
      url: https://tt.me/Hockey2019
      id: 579249368771
      token: _WJ5Jt0ksotmic5llAnm7DJNvXO8WAce8AIBpLGVW-o
  broadcast:
    enabled: true
    executor:
      corePoolSize: 2
      maxPoolSize: 4
  rss:
    enabled: true
    token: Iu9O0wVu2dtllKK8MV-Sw9gbFMkM8Z5cLYCTnl8PMGg
    executor:
      corePoolSize: 2
      maxPoolSize: 4
  webhook:
    elama:
      ids:
      schemeId: